name: gifthub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.3.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.1.0
  infinite_scroll_pagination: ^5.0.0
  video_player: ^2.9.5
  chewie: ^1.7.1
  carousel_slider: ^5.0.0
  get_storage: ^2.1.1
  flutter_meedu: ^9.1.1
  video_player_win: ^3.1.1
  flutter_launcher_icons: ^0.14.3
  dropdown_button2: ^2.3.9
  animated_bottom_navigation_bar: ^1.4.0
  connectivity_plus: ^ 6.1.4
  photo_view: ^0.15.0
  window_size: ^0.1.0
  go_router: ^15.1.2
  url_strategy: ^0.3.0
  intl: ^0.20.2

  webview_flutter: ^4.11.0
  url_launcher: ^6.3.1
  http: ^1.4.0
  flutter_rating_bar: ^4.0.1
  webview_windows: ^0.4.0
  web: ^1.1.1

  universal_html: ^2.2.4

  webview_flutter_web: ^0.2.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  msix: ^3.16.9

flutter:
  generate: true
  assets:
    - lib/env_config.dart
    - assets/
    - assets/images/no_image.png

  uses-material-design: true

  fonts:
    - family: plantype
      fonts:
        - asset: fonts/plantype.otf
    - family: segoeui
      fonts:
        - asset: fonts/segoeui.ttf
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
        - asset: fonts/NotoSans-Bold.ttf

